config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root to: 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  resourcify
  belongs_to :author
  has_many :book_genres, dependent: :destroy
  has_many :genres, through: :book_genres

  has_one_attached :cover, dependent: :purge_later

  validates :title, presence: { message: 'Please provide a title' }
  validates :date_published, presence: { message: 'Please set a publication date' }
  validate :past_date

  def past_date
    errors.add(:date_published, 'Date published must be in the past.') if date_published >= Date.today
  end
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :book_genres, dependent: :destroy
    has_many :books, through: :book_genres
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_role

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable  

  def set_role
    add_role :user if roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::Error, with: :nope

  private

  def forbidden
    flash[:alert] = 'You are not authorized to perform that action!'
    redirect_to(request.referrer || root_path)
  end

  def nope
    flash[:alert] = 'Nah m8, canny do that!'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_authorization

  before_action :set_book, only: %i[show edit update destroy]
  before_action :set_authors_and_genres, only: %i[new edit create]

  def new
    @book = Book.new
  end

  def index
    @books = Book.order(title: :asc)
  end

  def create
    # render json: params
    @book = Book.new(book_params)
    begin
      @book.save
      redirect_to @book
    rescue StandardError
      flash.now[:errors] = @book.errors.messages.values.flatten
      render 'new'
    end
  end

  def update
    # render json: book_params
    @book.update(book_params)
    redirect_to @book
  end

  def edit; end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  def show; end

  private

  def book_params
    params.require(:book).permit(:title, :publisher, :date_published, :cover, :author_id, genre_ids: [])
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def set_authors_and_genres
    @authors = Author.order(:last_name)
    @genres = Genre.order(:name)
  end

  def check_authorization
    authorize Book
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/boooks_helper.rb
module BoooksHelper
end

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'layouts/form' %>

app/views/books/index.html.erb
<h1>Books</h1>

<% if policy(Book).new? %>
    <p><%= link_to "New Book", new_book_path %></p>
<% end %>

<table>
    <tr>
        <th>Cover</th>
        <th id= "table_title">Title</th>
        <th id= "table_author">Author</th>
    </tr>
    <% @books.each do |book| %>
        <tr>
            <td><%= cl_image_tag book.cover.key, crop: :scale, width: 50, cloud_name: 'bbart121' if book.cover.attached? %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.author.full_name %></td>
        </tr>
    <% end %>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'layouts/form' %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h3>By <%= @book.author.full_name %></h3>
<% if @book.cover.attached? %>
    <%= cl_image_tag @book.cover.key, crop: :scale, width: 150, cloud_name: 'bbart121' %>
<% end %>
<h5>Genres: <%= @book.genres.map { |g| g.name }.join(", ") %></h5>
<p>Publisher: <%= @book.publisher %></p>
<p>Published: <%= @book.date_published %></p>
<p>
    <%= link_to "<<Back to Book List", books_path %>
    <% if policy(@book).update? %>
        |
        <%= link_to "Edit", edit_book_path(@book) %>
    <% end %>
    <% if policy(@book).destroy? %>
        |
        <%= link_to "Delete", @book, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/_form.html.erb
<%= form_with model: @book do |f| %>
    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :cover %>
        <%= f.file_field :cover %>
    </p>
    <p>
        <%= f.label :author_id %>
        <%= f.collection_select :author_id, @authors, :id, :full_name %>
    </p>
    <p>
        <%= f.label :publisher %>
        <%= f.text_field :publisher %>
    </p>
    <p>
        <%= f.label :date_published %>
        <%= f.date_field :date_published %>
    </p>
    <p>
        <%= f.label :genres %>
        <%= f.collection_check_boxes :genre_ids, @genres, :id, :name %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/layouts/_topnav.html.erb
<section id='topnav'>
    <% if user_signed_in? %>
        <%= current_user.email %>
        |
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to 'Login', new_user_session_path %>
        |
        <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DatabaseLesson</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/topnav' %>
    <% if flash[:errors] %>
      <section>
        <% flash[:errors].each do |error| %>
          <p><%= error %></p>
        <% end %>
      </section>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>